import './globals.css'
import type { Metadata } from 'next'
import Sidebar from './components/layout/Sidebar'
import Dock from './components/dock/Dock'

export const metadata: Metadata = {
  title: 'Scene Swift',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Dock />
      </body>
    </html>
  )
}
